jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}

spring:
  thymeleaf:
    prefix: classpath:static/
    check-template-location: false
    suffix: .html
    mode: HTML
    cache: false
    template-resolver-order: 0
  datasource:
    url: ENC(kCaJ19CCvhVn+FDaZwVYLm5MTMcdPwSZYGZmZIroFBqRaJNBddUJ4n/zkjp/OEeUEl2gR+7oeTFBRLEqr8hgcoiXY61o5EbPUUkCFofQhzoAyctX0jIDZtYg+pADf6StxI6C7dLEPvY3L5EnRfyR9/xVQg4BF6kI)
    username: ENC(hgautNkYDOIahaI9iMVqKg==)
    password: ENC(SlKSYwJ0FsK+68RlxooJQa/fjm2RRqc1)
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  redis:
    host: ENC(A6gxzk8z82nukIaLbK+x7TsbwK1M4suhKD0W3UEROJGM+nLMLX1tNg==)
    port: 12003
    password: ENC(b7dUKiZI/MgWAVru//EbNXaNfRsvUmqM)

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace

decorator:
  datasource:
    p6spy:
      enable-logging: false

server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
  port: 8443
  servlet:
    session:
      cookie:
        http-only: true
        secure: true