# jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
spring:
  datasource:
    url: ENC(njg2iXXl9ktztWBBCet3A2c6QXkrUgp4nR2Z3YNJGYBUNen+Lq6AFf63yGYsYbJbQjc6rUEpMaKzJ6zbBbyr3hMLrmgWCB87jnEWmI+h6QUONWe/EN6LNJ3DNcyZZ8DTdcx9gWaBNPm+ttBDldFOkA==)
    username: ENC(hgautNkYDOIahaI9iMVqKg==)
    password: ENC(SlKSYwJ0FsK+68RlxooJQa/fjm2RRqc1)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace